export const billingData = [
  {
    plan: "Basic plan - Dec 2022",
    amount: "USD $10.00",
    date: "Dec 1, 2022",
    status: "Paid",
    users: [
      "/assets/avatar.png",
      "/assets/avatar-2.png",
      "/assets/avatar-3.png",
      "/assets/avatar-4.png",
      "/assets/avatar-5.png",
      "/assets/avatar.png",
    ],
  },
  {
    plan: "Basic plan - Nov 2022",
    amount: "USD $10.00",
    date: "Nov 1, 2022",
    status: "Paid",
    users: [
      "/assets/avatar.png",
      "/assets/avatar-2.png",
      "/assets/avatar-3.png",
      "/assets/avatar-4.png",
      "/assets/avatar-5.png",
      "/assets/avatar.png",
      "/assets/avatar.png",
    ],
  },
  {
    plan: "Basic plan - Oct 2022",
    amount: "USD $10.00",
    date: "Oct 1, 2022",
    status: "Paid",
    users: [
      "/assets/avatar.png",
      "/assets/avatar-2.png",
      "/assets/avatar-3.png",
      "/assets/avatar-4.png",
      "/assets/avatar-5.png",
      "/assets/avatar.png",
    ],
  },
  {
    plan: "Basic plan - Sept 2022",
    amount: "USD $10.00",
    date: "Sept 1, 2022",
    status: "Paid",
    users: ["/assets/avatar.png", "/assets/avatar-2.png", "/assets/avatar-3.png"],
  },
  {
    plan: "Basic plan - Aug 2022",
    amount: "USD $10.00",
    date: "Aug 1, 2022",
    status: "Paid",
    users: [
      "/assets/avatar.png",
      "/assets/avatar-2.png",
      "/assets/avatar-3.png",
      "/assets/avatar-4.png",
    ],
  },
  {
    plan: "Basic plan - Jul 2022",
    amount: "USD $10.00",
    date: "Jul 1, 2022",
    status: "Paid",
    users: [
      "/assets/avatar.png",
      "/assets/avatar-2.png",
      "/assets/avatar-3.png",
      "/assets/avatar-4.png",
    ],
  },
  {
    plan: "Basic plan - Jun 2022",
    amount: "USD $10.00",
    date: "Jun 1, 2022",
    status: "Paid",
    users: [
      "/assets/avatar.png",
      "/assets/avatar-2.png",
      "/assets/avatar-3.png",
    ],
  },
];
